apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: order-service
  name: order-service
spec:
  ports:
  - port: 8071
    protocol: TCP
    targetPort: 8071
  selector:
    app: order-service
status:
  loadBalancer: {}